### ISSUE TITLE
Add min_version (>= 1.1.0) to dplyr in DESCRIPTION 

### ISSUE THREAD

**Issue by ottvahtrik** [bruigtp/flowchart#1]
Hi there!
First of all, thank you for creating this package! It looks really promising!

I wanted to point out, that there is a missing `min_version` for `{dplyr}` in `DESCRIPTION`. I tried to run the example of `flowchart::fc_filter()` and got the following error:

![image](https://github.com/bruigtp/flowchart/assets/47562074/663f52a5-2ac1-4136-b9ed-a115522ecc58)

The error happened because I had `{dplyr} 1.0.10` installed.

**Comment by pasahe** [comment]
Dear @ottvahtrik, 

Thanks for the post. I'm glad that this package can help you.

It's true that the package depends on a minimum version of `{dplyr}` to run. For the next version, I will update the `DESCRIPTION` to include this minimum version for `{dplyr} (>= 1.1.0)`. Thanks for pointing this out!
