### ISSUE TITLE
Compute percentages from total and not only from parent leaf

### ISSUE THREAD

**Issue by tvroylandt** [bruigtp/flowchart#11]
Hi, 

Thanks for the great package I've discovered at useR !

Would it be possible to add a feature so that percentages would be computed with the total number at the beginning of the flowchart and not only from the parent leaf ?

Thank you !

**Comment by pasahe** [comment]
Hi @tvroylandt,

I am very glad that you liked the presentation at useR and that you find this package useful. 

It's a very good idea and it would be a very nice feature to add in the next release of the package. We will add it as a new argument available to the `fc_filter()` and `fc_split()` functions.

Thanks for the feedback!

**Comment by pasahe** [comment]
Dear @tvroylandt,

I have added a new argument called `perc_total` to the functions `fc_split()` and `fc_filter()`. If you set this argument to TRUE, then percentages will be calculated using the total number of initial rows, and not the parent leaf. You can try this new argument in the development version on github. The next version 0.5.0 will be released in CRAN soon.

**Comment by tvroylandt** [comment]
Awesome ! I tested it and this is perfect. Thanks a lot @pasahe
