### ISSUE TITLE
BugFix: fc_export() format argument does not work

### ISSUE THREAD

**Issue by vmrothe** [bruigtp/flowchart#12]
Hi, 
after your presentation at the useR conference, I really wanted to try out the package. Thanks for all the work you've already put into it!

Unfortunately, the following does not work for me:
when I export the flowchart using fc_export() specifying the format using the "format" argument of the function, it is not correctly appended (on Windows). 

To be clear: this works perfectly fine: 
`fc_export("flowchart.png", width = 2500, height = 2000, res = 700)`
this does not:
`fc_export("flowchart", format="png", width = 2500, height = 2000, res = 700)`
as the extension is not put to the path.

Thank you!

**Comment by pasahe** [comment]
Dear @vmrothe,

Thank you for the post. Glad you found the package useful!

It's true that the `fc_export()` function did not behave as expected when the extension was not specified in the filename. I have fixed this and committed it to github. So if you install the development version with the following command, you should not have problems anymore: `remotes::install_github('bruigtp/flowchart')`.

Thanks for noticing this.

**Comment by vmrothe** [comment]
Perfect, thanks a lot! :)
