### ISSUE TITLE
Feature request: Add title to flowchart

### ISSUE THREAD

**Issue by vmrothe** [bruigtp/flowchart#14]
Good morning, 

I wonder whether there is a possibility to add text, namely a title, to a drawn flowchart? If not, would you mind adding the option to the fc_draw() function? 

Thanks a lot!

**Comment by pasahe** [comment]
Dear @vmrothe,

Thanks for your valuable insights on the package. I have added the argument `title` to the function `fc_draw()` to have the possibility to add a title to the flowchart. I also added the arguments `title_x`, `title_y`, `title_fs`, `title_fface` and `title_ffamily` for the customization of the title. You can find the package updated with these new arguments in the development version on github.

Thank you very much!

**Comment by vmrothe** [comment]
Thanks a lot for adding that feature. I really appreciate that. Absolutely amazing :)
