### ISSUE TITLE
Update `fc_export()` to support vector formats and use `ragg` instead of `grDevices`

### ISSUE THREAD

**Issue by kenkomodo** [bruigtp/flowchart#16]
I sometimes prefer vectorized image formats vs bitmap image formats to keep quality when scaling.

To that end, I'll be submitting a PR for consideration that updates `fc_export()` to add vector formats as an output option. 

Also going to add a suggested dependency and conditional use of `ragg` (from the `tidyverse` team) in place of `grDevices` when the user has `ragg` installed. This will improve cross-platform consistency, file generation performance, and result in overall higher quality comapred to `grDevices` - see the documentation [here](https://ragg.r-lib.org/index.html).

**Comment by pasahe** [comment]
Hi @kenkomodo!

Thanks for your time and work on the package. It is definitely very nice to have other formats instead of bitmap formats. Also, I haven't worked much with `ragg` but I see that the usage is the same and it improves the performance. Great enhancement!
