### ISSUE TITLE
Adding this package to conda-forge

### ISSUE THREAD

**Issue by aseltmann** [bruigtp/flowchart#18]
Thank you for this amazing package - I just wanted to quickly ask if you would feel comortable adding this package to `conda-forge` as well? I use conda for my reproducible research setups and would greatly appreciate it to have `r-flowchart` in `conda-forge`! 

The process to contribute packages is described here: https://conda-forge.org/docs/maintainer/adding_pkgs/

All the best!
Alva

**Comment by pasahe** [comment]
Dear @aseltmann,

Thanks for the post. It would be nice to have the package in `conda-forge` as well. I will submit it in the next few days.

Best regards,
Pau
