### ISSUE TITLE
Idea: enable split starts, needed e.g. for data harmonization

### ISSUE THREAD

**Issue by aseltmann** [bruigtp/flowchart#19]
HI @pasahe,
Not sure if this is something in scope for this project - I have a project where I harmonized data from 4 databases into one, and then excluded some duplicates etc. That means for the participant flow that I start with 4 split boxes, which are then merged into one, and which is then possibly split again. I attached an example of such a split start below (not a participant flow, but I think you get the idea). Do you think this could be implemented? Or is that already possible with the current functionality and I just missed it? All the best! 

<details>
<summary>See example</summary>

![Flowchart-for-database-selection](https://github.com/user-attachments/assets/d74afbb0-6fc6-4f48-9c49-1ed1606bc18e)

CC BY 4.0 Application of lean healthcare in hospital services: A review of the literature (2007 to 2017) - Scientific Figure on ResearchGate. Available from: https://www.researchgate.net/figure/Flowchart-for-database-selection_fig1_326664290 [accessed 6 Nov 2024]
</details>

**Comment by pasahe** [comment]
Hi @aseltmann,

There isn't a specific function to merge 4 boxes into one, but there is a workaround that can achieve this using `fc_stack()` and `unite=TRUE`. For example using the `iris` dataset:

`
fc1 <- iris |>
  as_fc(hide = TRUE) |> 
  fc_split(Species)

fc2 <- iris |> 
  as_fc() |> 
  fc_filter(Sepal.Length > 5)

fc_stack(list(fc1, fc2), unite = TRUE) |> 
  fc_draw()
`

If you want to use `hide=TRUE` in `as_fc()`  you have to update to the development version, as there was a bug in the argument when interacting with `fc_split()`. I plan to release a new CRAN version in the next few days.

Hopefully this will solve your problem.

**Comment by aseltmann** [comment]
Thanks for this quick solution - that actually solved my original problem, although there were some other problems I faced (and I did not really need the convenience of working directly from my dataframe this package provides), so in the end I looked around a bit more and found the `consort` package a bit more tuned to my specific needs.

Still, maybe this is of interest to you as feedback:
- `fc_stack()` with `unite = TRUE` seems to have problems with the arrows from boxes with different heights
- I couldn't figure out how to print a bold font in the plot

<details>
<summary>example plot</summary>

```R
label_A = "Primary database A\n
text text text text text text 
text text text text text text 
text text text text text text 
text text text text text text"
label_B = "Primary database B\n
text text text text text text 
text text text text text text 
text text text text text text 
text text text text text text"
label_C = "Primary database C\n
text text text text text text 
text text text text text text 
text text text text text text 
text text text text text text"
label_D = "Primary database D\n
text text text text text text 
text text text text text text 
text text text text text text 
text text text text text text"
label_selA = "case selection criteria:
text text text text text text"
label_selB = "case selection criteria:
text text text text text text
text text text text text text"
label_selC = "case selection criteria:
text text text text text text"
label_selD = "case selection criteria:
text text text text text text"
fc1 <- flowchart::as_fc(N = 4, hide = TRUE) |>
  flowchart::fc_split(N = c(1, 1, 1, 1),
                      label = c(label_A, label_B, label_C, label_D),
                      text_pattern = "{label}") |>
  flowchart::fc_filter(N = c(1, 1, 1, 1),
                       label = c(label_selA, label_selB, label_selC, label_selD),
                       text_pattern = "{label}")

fc2 <- flowchart::as_fc(N = 260) |>
  flowchart::fc_filter(N = 240, label = expression(bold(Final)), show_exc = TRUE)

flowchart::fc_stack(list(fc1, fc2), unite = TRUE) |>
  flowchart::fc_draw() |>
  flowchart::fc_export("test.png", width = 1000, height = 800)
```

![test](https://github.com/user-attachments/assets/ccb0e81a-4f3b-4a6d-9842-c457abb7f893)

</details>

**Comment by pasahe** [comment]
Hi @aseltmann,

I'm sorry it didn't work for you. It's true that `unite=TRUE` has weird behavior when boxes are of different heights, this is inherited from the `Gmisc` package when calling `connectGrob()` with `type=N`. A possible workaround for this would be to add an extraline with `\n` at the end of each of the shorter boxes to make them the same height. Regarding the bold expression, I will add the functionality to recognize expressions specified in the text. For now, the only possible option is to make all text in the box bold by defining `text_ff = 2`.

Thanks for the feedback!

**Comment by aseltmann** [comment]
Thank you for taking the time and your openness for feedback! I will close the issue because the original question was solved. All the best!

**Comment by aseltmann** [comment]
Thank you for taking the time and your openness for feedback! I will close the issue because the original question was solved. All the best!
