### ISSUE TITLE
fc_filter() does not work well when it is used after fc_split()

### ISSUE THREAD

**Issue by yohei-h** [bruigtp/flowchart#20]
Hi All,

I am in trouble with fc_filter() after fc_split(). Below are the problems.
- The heights of the two branches are not aligned.
- The percents do not add up to 100%. e.g. The sum of "102 (100%) aa" and "Excluded 16 (14%)" will become 118 (114%).

Could anyone help to deal with these matters?
Please find attached the image and R codes.

```
library(tidyverse)
library(flowchart)
df_iris <- iris %>% 
    mutate(Group = ifelse(Sepal.Length > 5, 1, 0),
           Condition1 = ifelse(Sepal.Width > 4, 1, 0),
           Condition2 = ifelse(Petal.Length > 1.5, 1, 0))  

df_iris

fc <-  df_iris %>% 
    as_fc(label = "Iris", text_pattern = "{n} ({perc}%) {label}", text_padding = 0.7, text_fs = 10) %>% 
    fc_split(Group, text_pattern = "{n} ({perc}%) {label}", round_digits = 0, text_padding = 0.7, text_fs = 10, offset = 0.1) %>% 
    # 0
    fc_filter(sel_group = 0, Condition1 == 0, label = "a", show_exc = T, text_pattern = "{n} ({perc}%) {label}", round_digits = 0, text_padding = 0.7, text_fs = 10, text_padding_exc = 0.7, text_fs_exc = 9) %>%
    fc_filter(sel_group = 0, Condition2 == 1, label = "b", show_exc = T, text_pattern = "{n} ({perc}%) {label}", round_digits = 0, text_padding = 0.7, text_fs = 10, text_padding_exc = 0.7, text_fs_exc = 9) %>%
    # 1
    fc_filter(sel_group = 1, Condition1 == 0, label = "aa", show_exc = T, text_pattern = "{n} ({perc}%) {label}", round_digits = 0, text_padding = 0.7, text_fs = 10, text_padding_exc = 0.7, text_fs_exc = 9) %>%
    fc_filter(sel_group = 1, Condition2 == 1, label = "bb", show_exc = T, text_pattern = "{n} ({perc}%) {label}", round_digits = 0, text_padding = 0.7, text_fs = 10, text_padding_exc = 0.7, text_fs_exc = 9) %>%
    fc_draw()
```

![Screenshot 2024-11-09 at 10 17 19 PM](https://github.com/user-attachments/assets/f499a573-e30d-4d60-8dde-ce5b5c72706d)

**Comment by yohei-h** [comment]
Hi @ pasahe,

Thank you for your reply. I now understand that `fc_filter()` should not be used separately for both branches. But as you say, the problem will remain if the inclusion criteria are different (= asymmetrical) between the two branches.
Looking forward to an updated version of this great package! 
Thanks so much for your efforts.

**Comment by pasahe** [comment]
Dear @yohei-h,

The bug in the `sel_group` argument is now fixed in the new development version. Now your example should work and produce the desired flowchart. However, in your case it would be better practice to call `fc_filter()` directly after `fc_split()` and it will be applied to both groups directly, as we said before. Even if there is an asymmetric inclusion criterion, you can have a filter variable in your dataset that applies a different logic in both groups, so it wouldn't always be necessary to use the `sel_group' argument in this setting.

Thank you!

**Comment by yohei-h** [comment]
Dear @pasahe,

Thanks so much for the quick updates!
