### ISSUE TITLE
Idea: Introduce a control of direction the flowchart propagation.

### ISSUE THREAD

**Issue by baszukpiotr** [bruigtp/flowchart#21]
Hi,
It would be useful to introduce the ability to control the direction of flowchart propagation. For example, I would like to split categories so that the branches appear not below but to the right or left of the last node. The package in its current version is very useful for quickly creating flowcharts with information about individual categories and the number of observations in each of them, but it lacks functionality for layout control.

Take care!

**Comment by pasahe** [comment]
Dear @baszukpiotr,

Thanks for the post. This would indeed be a nice feature to add to the package, increasing the flexibility of our tool. However, implementing this option requires reprogramming some of the current functions, so it will take some time. I will try to include it in the future.
