### ISSUE TITLE
question

### ISSUE THREAD

**Issue by higgi13425** [bruigtp/flowchart#3]
how can you create a line for each reason for exiting a study?
i.e.
12 left due to flare of a disease
3 left due to rash
2 left due to headache

**Comment by higgi13425** [comment]
is this already possible?

**Comment by pasahe** [comment]
Yes, this is possible using the `fc_modify()` function. You can see an example of how this can be done in the vignette's [Example 2](https://bruigtp.github.io/flowchart/articles/flowchart.html#example-2). 
 
In the first piece of code is where all the text for the reason for exiting a study is created: `label_exc1` and `label_exc2`. Then, after creating the basic flowchart we can use the `fc_modify()` function to replace the original text of the desired boxes for the previously created text in this specific line:

`text = case_when(id == 11 ~ label_exc1, id == 13 ~ label_exc2, TRUE ~ text)`

Hope this helps you. 

Thanks for the post!

**Comment by higgi13425** [comment]
This is really great! Thanks for creating and sharing this package!
