### ISSUE TITLE
feature request: control padding around text in boxes

### ISSUE THREAD

**Issue by higgi13425** [bruigtp/flowchart#8]
It would be nice to be able to control the padding around text in boxes with the t,r,b,l arguments (top, bottom, left, right)

**Comment by pasahe** [comment]
Thanks for your feedback! We will explore a way to control the box size relative to the text in future versions of the package. It would definitely be a nice feature to add.

**Comment by pasahe** [comment]
Dear @higgi13425,

The choice of the text padding is also a choice inherited from the {Gmisc} package, so unfortunately I am not able to change it.

**Comment by pasahe** [comment]
Dear @higgi13425,

I have added a new argument called `text_padding` to control the padding of the text. The default is 1, so you can set a number between 0 and 1 to decrease the padding, and a number greater than 1 to increase it.
